apiVersion: v1
kind: Service
metadata:
  name: was
  annotations:
    # [핵심] AWS 클라우드 컨트롤러에게 "내부용 NLB를 만들어달라"고 요청
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  selector:
    app: was
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
  # [변경] ClusterIP -> LoadBalancer
  # 로컬/테스트 환경에서는 ClusterIP처럼 동작하다가, AWS 환경이 갖춰지면 NLB가 됩니다.
  type: LoadBalancer